### ISSUE TITLE
Check if price range works correctly

### ISSUE THREAD

**Issue by vyorkin** [findify/findify-js#24]
its broken on staging:

![broken-range](https://user-images.githubusercontent.com/988849/31317023-01d3a81e-ac42-11e7-8f27-afbc2075f0a6.gif)

https://github.com/findify/findify-js/blob/37e6ce8ab76ce12a3d341f30347ac8e4d93eead1/packages/mjs/src/features/search/provider/helpers.ts#L26

**Comment by Bitaru** [comment]
solved
