### ISSUE TITLE
Add type declarations to the react-connect package

### ISSUE THREAD

**Issue by markjaniczak** [findify/findify-js#614]
I'm creating custom React components using the `react-connect` package using typescript and have found it doesn't ship with type declarations like the other packages do. I can't find much documentation available for this package so I was hoping I could refer to the available types.

**Comment by Bitaru** [comment]
@markjaniczak Hi Mark, thank you for your feedback! We will add it to our backlog (in month or so it will be added). As far it is not implemented you can refer to our documentation https://developers.findify.io/page/findify-react-connect-reference , in case you have other questions please ask Support team.

**Comment by markjaniczak** [comment]
I've run `yarn build:types` in my local copy of `react-connect` which looks to generate type declarations that you guys have made. I'm using `patch-package` to keep them around for now.

Some of the types that process builds don't match the documentation you've provided though. For example the documentation says only `apiKey` is a required property but the generated types mark everything but `storeKey` as required.

**Comment by vgoloviznin** [comment]
This will be resolved #653 (v6.17.0)
